import 'dart:io';

import 'package:drift/drift.dart';
import 'package:drift/native.dart';
import 'package:path/path.dart' as p;
import 'package:path_provider/path_provider.dart';

part 'database.g.dart'; // Generated by drift_dev

// ── Table definitions ──

class Conversations extends Table {
  TextColumn get id => text()();
  TextColumn get source => text()();
  TextColumn get title => text()();
  TextColumn get startedAt => text().nullable()();
  TextColumn get importedAt => text()();
  IntColumn get isWork => integer().nullable()();

  @override
  Set<Column> get primaryKey => {id};
}

class Projects extends Table {
  TextColumn get id => text()();
  TextColumn get name => text()();
  TextColumn get summary => text().nullable()();
  TextColumn get status => text().withDefault(const Constant('active'))();
  TextColumn get startedAt => text().nullable()();
  TextColumn get endedAt => text().nullable()();
  TextColumn get roleId => text().nullable().references(Roles, #id)();

  @override
  Set<Column> get primaryKey => {id};
}

class Skills extends Table {
  TextColumn get id => text()();
  TextColumn get name => text()();
  TextColumn get category => text()();

  @override
  Set<Column> get primaryKey => {id};
}

class Achievements extends Table {
  TextColumn get id => text()();
  TextColumn get summary => text()();
  TextColumn get impact => text().nullable()();
  TextColumn get achievedAt => text().nullable()();

  @override
  Set<Column> get primaryKey => {id};
}

class Roles extends Table {
  TextColumn get id => text()();
  TextColumn get title => text()();
  TextColumn get company => text().nullable()();
  TextColumn get startedAt => text().nullable()();
  TextColumn get endedAt => text().nullable()();

  @override
  Set<Column> get primaryKey => {id};
}

// Junction tables

class ConversationProjects extends Table {
  TextColumn get conversationId =>
      text().references(Conversations, #id)();
  TextColumn get projectId => text().references(Projects, #id)();

  @override
  Set<Column> get primaryKey => {conversationId, projectId};
}

class ProjectSkills extends Table {
  TextColumn get projectId => text().references(Projects, #id)();
  TextColumn get skillId => text().references(Skills, #id)();

  @override
  Set<Column> get primaryKey => {projectId, skillId};
}

class ProjectAchievements extends Table {
  TextColumn get projectId => text().references(Projects, #id)();
  TextColumn get achievementId =>
      text().references(Achievements, #id)();

  @override
  Set<Column> get primaryKey => {projectId, achievementId};
}

// ── Database class ──

@DriftDatabase(tables: [
  Conversations,
  Projects,
  Skills,
  Achievements,
  Roles,
  ConversationProjects,
  ProjectSkills,
  ProjectAchievements,
])
class AppDatabase extends _$AppDatabase {
  AppDatabase() : super(_openConnection());

  AppDatabase.forTesting(super.e);

  @override
  int get schemaVersion => 1;

  // ── Conversations ──

  Future<bool> conversationExists(String convId) async {
    final row = await (select(conversations)
          ..where((c) => c.id.equals(convId)))
        .getSingleOrNull();
    return row != null;
  }

  Future<void> insertConversation(Insertable<Conversation> row) =>
      into(conversations).insertOnConflictUpdate(row);

  Future<void> updateIsWork(String convId, bool isWork) =>
      (update(conversations)..where((c) => c.id.equals(convId)))
          .write(ConversationsCompanion(isWork: Value(isWork ? 1 : 0)));

  // ── Skills (dedup by normalized name) ──

  Future<String> upsertSkill({
    required String id,
    required String name,
    required String category,
  }) async {
    final normalized = name.trim().toLowerCase();
    final existing = await (select(skills)
          ..where((s) => s.name.equals(normalized)))
        .getSingleOrNull();
    if (existing != null) return existing.id;

    await into(skills).insert(SkillsCompanion.insert(
      id: id,
      name: normalized,
      category: category,
    ));
    return id;
  }

  // ── Projects ──

  Future<String> upsertProject({
    required String id,
    required String name,
    String? summary,
    String? status,
    String? startedAt,
    String? endedAt,
    String? roleId,
  }) async {
    final normalized = name.trim().toLowerCase();
    final existing = await (select(projects)
          ..where((p) => p.name.lower().equals(normalized)))
        .getSingleOrNull();
    if (existing != null) return existing.id;

    await into(projects).insert(ProjectsCompanion.insert(
      id: id,
      name: name,
      summary: Value(summary),
      status: Value(status ?? 'active'),
      startedAt: Value(startedAt),
      endedAt: Value(endedAt),
      roleId: Value(roleId),
    ));
    return id;
  }

  Future<void> updateProject(ProjectsCompanion data) =>
      (update(projects)..where((p) => p.id.equals(data.id.value)))
          .write(data);

  // ── Achievements ──

  Future<String> insertAchievement({
    required String id,
    required String summary,
    String? impact,
    String? achievedAt,
  }) async {
    await into(achievements).insert(AchievementsCompanion.insert(
      id: id,
      summary: summary,
      impact: Value(impact),
      achievedAt: Value(achievedAt),
    ));
    return id;
  }

  // ── Roles ──

  Future<void> insertRole(Insertable<Role> data) =>
      into(roles).insert(data);

  Future<void> updateRole(RolesCompanion data) =>
      (update(roles)..where((r) => r.id.equals(data.id.value))).write(data);

  Future<void> linkProjectToRole(String projectId, String roleId) =>
      (update(projects)..where((p) => p.id.equals(projectId)))
          .write(ProjectsCompanion(roleId: Value(roleId)));

  // ── Junction tables ──

  Future<void> linkConversationProject(String convId, String projId) =>
      into(conversationProjects).insertOnConflictUpdate(
        ConversationProjectsCompanion.insert(
          conversationId: convId,
          projectId: projId,
        ),
      );

  Future<void> linkProjectSkill(String projId, String skillId) =>
      into(projectSkills).insertOnConflictUpdate(
        ProjectSkillsCompanion.insert(
          projectId: projId,
          skillId: skillId,
        ),
      );

  Future<void> linkProjectAchievement(String projId, String achId) =>
      into(projectAchievements).insertOnConflictUpdate(
        ProjectAchievementsCompanion.insert(
          projectId: projId,
          achievementId: achId,
        ),
      );

  // ── Queries ──

  Future<List<Project>> getAllProjects() async {
    final query = select(projects)
      ..orderBy([(p) => OrderingTerm.desc(p.startedAt)]);
    return query.get();
  }

  Future<List<Skill>> getAllSkills() =>
      (select(skills)..orderBy([(s) => OrderingTerm.asc(s.category),
        (s) => OrderingTerm.asc(s.name)])).get();

  Future<List<Achievement>> getAllAchievements() =>
      (select(achievements)
            ..orderBy([(a) => OrderingTerm.desc(a.achievedAt)]))
          .get();

  Future<List<Role>> getAllRoles() =>
      (select(roles)..orderBy([(r) => OrderingTerm.desc(r.startedAt)]))
          .get();

  Future<List<Project>> getProjectsForRole(String roleId) =>
      (select(projects)..where((p) => p.roleId.equals(roleId))).get();

  Future<List<Skill>> getSkillsForProject(String projectId) {
    final query = select(skills).join([
      innerJoin(
        projectSkills,
        projectSkills.skillId.equalsExp(skills.id),
      ),
    ])
      ..where(projectSkills.projectId.equals(projectId));

    return query.map((row) => row.readTable(skills)).get();
  }

  Future<void> deleteProject(String id) =>
      (delete(projects)..where((p) => p.id.equals(id))).go();

  Future<void> deleteSkill(String id) =>
      (delete(skills)..where((s) => s.id.equals(id))).go();

  Future<void> deleteAchievement(String id) =>
      (delete(achievements)..where((a) => a.id.equals(id))).go();

  Future<void> deleteRole(String id) =>
      (delete(roles)..where((r) => r.id.equals(id))).go();

  // ── Stats ──

  Future<Map<String, int>> getStats() async {
    final projectCount =
        await select(projects).get().then((r) => r.length);
    final skillCount =
        await select(skills).get().then((r) => r.length);
    final achievementCount =
        await select(achievements).get().then((r) => r.length);
    final roleCount =
        await select(roles).get().then((r) => r.length);
    return {
      'projects': projectCount,
      'skills': skillCount,
      'achievements': achievementCount,
      'roles': roleCount,
    };
  }
}

LazyDatabase _openConnection() {
  return LazyDatabase(() async {
    final dbFolder = await getApplicationDocumentsDirectory();
    final file = File(p.join(dbFolder.path, 'careeros.db'));
    return NativeDatabase.createInBackground(file);
  });
}
